/*
 * This file is generated by jOOQ.
 */
package io.lumine.cosmetics.storage.sql.mappings;


import io.lumine.cosmetics.storage.sql.mappings.tables.MccosmeticsProfile;
import io.lumine.cosmetics.storage.sql.mappings.tables.MccosmeticsProfileEquipped;

import java.util.Arrays;
import java.util.List;

import io.lumine.utils.lib.jooq.Catalog;
import io.lumine.utils.lib.jooq.Table;
import io.lumine.utils.lib.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>mccosmetics_profile</code>.
     */
    public final MccosmeticsProfile MCCOSMETICS_PROFILE = MccosmeticsProfile.MCCOSMETICS_PROFILE;

    /**
     * The table <code>mccosmetics_profile_equipped</code>.
     */
    public final MccosmeticsProfileEquipped MCCOSMETICS_PROFILE_EQUIPPED = MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            MccosmeticsProfile.MCCOSMETICS_PROFILE,
            MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED
        );
    }
}
