/*
 * This file is generated by jOOQ.
 */
package io.lumine.cosmetics.storage.sql.mappings;


import io.lumine.cosmetics.storage.sql.mappings.tables.MccosmeticsProfile;
import io.lumine.cosmetics.storage.sql.mappings.tables.MccosmeticsProfileEquipped;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mccosmetics_profile</code>.
     */
    public static final MccosmeticsProfile MCCOSMETICS_PROFILE = MccosmeticsProfile.MCCOSMETICS_PROFILE;

    /**
     * The table <code>mccosmetics_profile_equipped</code>.
     */
    public static final MccosmeticsProfileEquipped MCCOSMETICS_PROFILE_EQUIPPED = MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED;
}
