/*
 * This file is generated by jOOQ.
 */
package io.lumine.cosmetics.storage.sql.mappings.tables;


import io.lumine.cosmetics.storage.sql.mappings.DefaultSchema;
import io.lumine.cosmetics.storage.sql.mappings.Keys;
import io.lumine.cosmetics.storage.sql.mappings.tables.records.ProfileRecord;

import io.lumine.utils.lib.jooq.Field;
import io.lumine.utils.lib.jooq.ForeignKey;
import io.lumine.utils.lib.jooq.Name;
import io.lumine.utils.lib.jooq.Record;
import io.lumine.utils.lib.jooq.Row2;
import io.lumine.utils.lib.jooq.Schema;
import io.lumine.utils.lib.jooq.Table;
import io.lumine.utils.lib.jooq.TableField;
import io.lumine.utils.lib.jooq.TableOptions;
import io.lumine.utils.lib.jooq.UniqueKey;
import io.lumine.utils.lib.jooq.impl.DSL;
import io.lumine.utils.lib.jooq.impl.SQLDataType;
import io.lumine.utils.lib.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MccosmeticsProfile extends TableImpl<ProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mccosmetics_profile</code>
     */
    public static final MccosmeticsProfile MCCOSMETICS_PROFILE = new MccosmeticsProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfileRecord> getRecordType() {
        return ProfileRecord.class;
    }

    /**
     * The column <code>mccosmetics_profile.uuid</code>.
     */
    public final TableField<ProfileRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>mccosmetics_profile.name</code>.
     */
    public final TableField<ProfileRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    private MccosmeticsProfile(Name alias, Table<ProfileRecord> aliased) {
        this(alias, aliased, null);
    }

    private MccosmeticsProfile(Name alias, Table<ProfileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mccosmetics_profile</code> table reference
     */
    public MccosmeticsProfile(String alias) {
        this(DSL.name(alias), MCCOSMETICS_PROFILE);
    }

    /**
     * Create an aliased <code>mccosmetics_profile</code> table reference
     */
    public MccosmeticsProfile(Name alias) {
        this(alias, MCCOSMETICS_PROFILE);
    }

    /**
     * Create a <code>mccosmetics_profile</code> table reference
     */
    public MccosmeticsProfile() {
        this(DSL.name("mccosmetics_profile"), null);
    }

    public <O extends Record> MccosmeticsProfile(Table<O> child, ForeignKey<O, ProfileRecord> key) {
        super(child, key, MCCOSMETICS_PROFILE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ProfileRecord> getPrimaryKey() {
        return Keys.KEY_MCCOSMETICS_PROFILE_PRIMARY;
    }

    @Override
    public MccosmeticsProfile as(String alias) {
        return new MccosmeticsProfile(DSL.name(alias), this);
    }

    @Override
    public MccosmeticsProfile as(Name alias) {
        return new MccosmeticsProfile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MccosmeticsProfile rename(String name) {
        return new MccosmeticsProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MccosmeticsProfile rename(Name name) {
        return new MccosmeticsProfile(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
