/*
 * This file is generated by jOOQ.
 */
package io.lumine.cosmetics.storage.sql.mappings.tables.records;


import io.lumine.cosmetics.storage.sql.mappings.tables.MccosmeticsProfileEquipped;

import io.lumine.utils.lib.jooq.Field;
import io.lumine.utils.lib.jooq.Record2;
import io.lumine.utils.lib.jooq.Record4;
import io.lumine.utils.lib.jooq.Row4;
import io.lumine.utils.lib.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileEquippedRecord extends UpdatableRecordImpl<ProfileEquippedRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mccosmetics_profile_equipped.profile_uuid</code>.
     */
    public void setProfileUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mccosmetics_profile_equipped.profile_uuid</code>.
     */
    public String getProfileUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mccosmetics_profile_equipped.slot</code>.
     */
    public void setSlot(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mccosmetics_profile_equipped.slot</code>.
     */
    public String getSlot() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mccosmetics_profile_equipped.cosmetic_id</code>.
     */
    public void setCosmeticId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mccosmetics_profile_equipped.cosmetic_id</code>.
     */
    public String getCosmeticId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mccosmetics_profile_equipped.cosmetic_data</code>.
     */
    public void setCosmeticData(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mccosmetics_profile_equipped.cosmetic_data</code>.
     */
    public String getCosmeticData() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED.PROFILE_UUID;
    }

    @Override
    public Field<String> field2() {
        return MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED.SLOT;
    }

    @Override
    public Field<String> field3() {
        return MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED.COSMETIC_ID;
    }

    @Override
    public Field<String> field4() {
        return MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED.COSMETIC_DATA;
    }

    @Override
    public String component1() {
        return getProfileUuid();
    }

    @Override
    public String component2() {
        return getSlot();
    }

    @Override
    public String component3() {
        return getCosmeticId();
    }

    @Override
    public String component4() {
        return getCosmeticData();
    }

    @Override
    public String value1() {
        return getProfileUuid();
    }

    @Override
    public String value2() {
        return getSlot();
    }

    @Override
    public String value3() {
        return getCosmeticId();
    }

    @Override
    public String value4() {
        return getCosmeticData();
    }

    @Override
    public ProfileEquippedRecord value1(String value) {
        setProfileUuid(value);
        return this;
    }

    @Override
    public ProfileEquippedRecord value2(String value) {
        setSlot(value);
        return this;
    }

    @Override
    public ProfileEquippedRecord value3(String value) {
        setCosmeticId(value);
        return this;
    }

    @Override
    public ProfileEquippedRecord value4(String value) {
        setCosmeticData(value);
        return this;
    }

    @Override
    public ProfileEquippedRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MccosmeticsProfileEquippedRecord
     */
    public ProfileEquippedRecord() {
        super(MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED);
    }

    /**
     * Create a detached, initialised MccosmeticsProfileEquippedRecord
     */
    public ProfileEquippedRecord(String profileUuid, String slot, String cosmeticId, String cosmeticData) {
        super(MccosmeticsProfileEquipped.MCCOSMETICS_PROFILE_EQUIPPED);

        setProfileUuid(profileUuid);
        setSlot(slot);
        setCosmeticId(cosmeticId);
        setCosmeticData(cosmeticData);
    }
}
